senzing-garage/aws-cloudformation-database-cluster

README.md
cloudformation.yaml
docs/README.md

#7 added lambda function to force scaling

---

CHANGELOG.md
cloudformation.yaml
docs/README.md

9 support for single database added

---

CHANGELOG.md
cloudformation.yaml

Issue 12.ron.0

---

cloudformation.yaml

#16 updated image versions

---

.github/workflows/copy-to-s3.yaml

Issue number: #30 
Automation to copy cloudformation.yaml to S3

Adding github action to copy cloudformation.yaml to S3

---

.github/workflows/copy-to-s3.yaml

Issue number: #32 
It was copying to the wrong location

Copying cloudformation.yaml to correct bucket

---

.github/workflows/copy-to-s3.yaml

Issue number: #34 
Files need to be public on S3

Making files public when copied to S3

---

cloudformation.yaml

#36 added autovacuum_max_workers=5

---

CHANGELOG.md
cloudformation.yaml
cloudformationV2.yaml

Issue 38.ron.0

---

CONTRIBUTING.md
README.md
docs/README.md

#39 Migrate from master to main

---

README.md

#42 updated readme

---

README.md

#44 updated readme

---

CHANGELOG.md
cloudformation.yaml

#46 updated image versions

---

cloudformation.yaml

#10 updated SecondsBeforeTimeout

---

CHANGELOG.md

#10 updated changelog

---

CHANGELOG.md
cloudformation.yaml

#54 updated database engine version

---

CHANGELOG.md
cloudformation.yaml

Issue 56.ron.0

---

README.md

#58 updated README

---

CHANGELOG.md
cloudformation.yaml

#62 updated to senzing 3.3.1

---

CHANGELOG.md
cloudformation.yaml

#64 updated to senzing 3.3.2

---

.github/CODEOWNERS
.github/workflows/copy-to-s3.yaml

#72 Update variables for secrets

---

CHANGELOG.md
cloudformation.yaml

#77 updated senzing and docker image versions

---

CHANGELOG.md
cloudformation.yaml

#79 update docker images and senzing version

---

.github/dependabot.yml
.github/workflows/add-to-project-garage-dependabot.yaml
.github/workflows/add-to-project-garage.yaml

Issue number: senzing-factory/build-resources#91

senzing-factory/build-resources#91 fix dependabot project status

---

.github/linters/.yaml-lint.yml
.github/workflows/add-labels-standardized.yaml
.github/workflows/add-to-project-garage-dependabot.yaml
.github/workflows/add-to-project-garage.yaml
.github/workflows/copy-to-s3.yaml
.github/workflows/lint-workflows.yaml

Issue number: senzing-factory/build-resources#69

senzing-factory/build-resources#69 add linting

---

CHANGELOG.md
cloudformation.yaml

#104 ready for versioned release
